# Generated by Django 4.2 on 2023-12-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='primary_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm.team'),
        ),
    ]
