# Generated by Django 4.2 on 2023-12-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_alter_employee_primary_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='primary_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm.employee'),
        ),
    ]
