# Generated by Django 4.2 on 2023-12-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_employee_primary_team_alter_team_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='primary_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hrm.employee'),
        ),
    ]
