# Generated by Django 4.2 on 2023-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_employee_primary_team_alter_team_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskduty',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
