# Generated by Django 4.2 on 2023-12-28 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_received',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='time_received',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
