# Generated by Django 4.2 on 2023-11-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
