# Generated by Django 4.2 on 2023-12-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_services_feedback_rating_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.SmallIntegerField(default=1),
        ),
    ]
