# Generated by Django 4.2 on 2023-12-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
